'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer"
import { useEffect } from "react";
import {CartProvider}  from "../context/cartContext";
import { SearchProvider } from "@/context/SearchContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 const metadata: Metadata = {
  title: "E-Commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

   useEffect(()=>{
    require('bootstrap/dist/js/bootstrap.bundle.min.js')
   },[])

  

  return (
    <html lang="en">
      <body
        className= {`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <SearchProvider>
        <CartProvider>
        <Navbar/>
        {children}
        <Footer/>
        </CartProvider>
        </SearchProvider>
        
      </body>
    </html>
  );
}
